### ISSUE TITLE
Create an AWS S3 Poll Bucket Connector

### ISSUE THREAD

**Issue by oscerd** [syndesisio/connectors#101]
This connector will be used to poll a bucket in AWS S3 and get all the files in it, without deleting the files.

**Comment by KurtStam** [comment]
@oscerd I think this is done? If so can you reference the PR here?

**Comment by oscerd** [comment]
Here it is, https://github.com/syndesisio/connectors/pull/105

Sorry but I thought there was a bot for this :-)

Good to know for the next PRs

**Comment by KurtStam** [comment]
If you reference the issue # in the commit message then the bot will correlate.

**Comment by oscerd** [comment]
I pur resolves #101 in the commit message
