### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by davsclaus** [syndesisio/connectors#17]
I wonder how @jimmidyson did the 0.2.1 release.

As we have done some more work on connectors and Camel, it would be good to get a new release out.

The connectors now
- configuration via spring boot (in application.properties)
- include data type for input and output
- automated via build the versions in the json files
- http get/post connectors now have component/global configuration of hostname/path, and the citizen user just add the additional context-path (if any)
- all examples updated

**Comment by rhuss** [comment]
I think @jimmidyson simply did it manually ;-) However, I have no idea about the proper Sonatype credentials, so we probably have to wait until jimmi is back.

**Comment by jimmidyson** [comment]
Simple mvn release process... @chirino released latest so closing this. Users simply need to be added to bintray org as i mentioned in email.
