### ISSUE TITLE
JSon schem using boolean and numeric types for their values

### ISSUE THREAD

**Issue by davsclaus** [syndesisio/connectors#2]
Hi @gashcrumb 

Wonder if you see a problem if we change the JSon schema to use boolean and numeric values for some of the fields.

You can see a JIRA and example here
https://issues.apache.org/jira/browse/CAMEL-10842

I think I can adjust the internal json emitter and parser in Apache Camel to support this and we can make the generated JSon schema a bit nicer.

**Comment by jimmidyson** [comment]
Yes please!

**Comment by gashcrumb** [comment]
Yeah, absolutely we can support that.  Also 'password' would be good for
protected fields.

**Comment by davsclaus** [comment]
We can debate whether password is only for password fields, but what about secret api tokens and the likes?

And some may wat to hide usernames as well, and therefore the json schema today has secret: true|false to indicate whether fields are considered sensitive.

**Comment by gashcrumb** [comment]
Ah, excellent, that works too...

**Comment by davsclaus** [comment]
So almost got the bits working now. The connector maven plugin needed some extra tweaks as well. When I got the bits correct at Apache then I will do the needed changes on the connectors JSon schema files here as well.
