### ISSUE TITLE
SNAPSHOT dependency in release

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/connectors#25]
https://ci.fabric8.io/job/ipaas-datamapper-pullreq/12/console

[ERROR] Failed to execute goal on project runtime: Could not resolve dependencies for project io.atlasmap:runtime:jar:1.9.5-SNAPSHOT: Failed to collect dependencies at com.redhat.ipaas:twitter-mention-connector:jar:0.3.1: Failed to read artifact descriptor for com.redhat.ipaas:twitter-mention-connector:jar:0.3.1: Could not find artifact org.apache.camel:camel-parent:pom:2.19.0-SNAPSHOT in apache.snapshots

**Comment by jimmidyson** [comment]
Yes we know we're using camel snapshots. We have no choice until there is a 2.19 release.

**Comment by KurtStam** [comment]
OK will enable grabbing snapshots in the data mapper project then.

**Comment by davsclaus** [comment]
There is EA builds now we use
https://repository.jboss.org/nexus/content/groups/ea/org/apache/camel/camel-core/
