### ISSUE TITLE
Wrong error message for HTTP connector's verifier

### ISSUE THREAD

**Issue by rhuss** [syndesisio/connectors#26]
When using the HTTP connector's verifier, the error message should be 'Required parameter missing', not 'unknown option':

```
curl -s http://192.168.64.3:32713/api/v1/verifier/http -X POST -H "Content-Type: application/json" -H "Accept: application/json" -d '{}' | jq .
```
```json
[
  {
    "scope": "PARAMETERS",
    "status": "ERROR",
    "errors": [
      {
        "code": "unknown-option",
        "description": "Unknown option httpUri",
        "parameters": [
          "httpUri"
        ],
        "attributes": {}
      },
      {
        "code": "unknown-option",
        "description": "Unknown option httpMethod",
        "parameters": [
          "httpMethod"
        ],
        "attributes": {}
      }
    ]
  }
]
```

E.g. for twitter it looks like:

```json
[
  {
    "scope": "PARAMETERS",
    "status": "ERROR",
    "errors": [
      {
        "code": "missing-option",
        "description": "accessToken should be set",
        "parameters": [
          "accessToken"
        ],
        "attributes": {}
      },
      {
        "code": "missing-option",
        "description": "accessTokenSecret should be set",
        "parameters": [
          "accessTokenSecret"
        ],
        "attributes": {}
      },
      {
        "code": "missing-option",
        "description": "consumerKey should be set",
        "parameters": [
          "consumerKey"
        ],
        "attributes": {}
      },
      {
        "code": "missing-option",
        "description": "consumerSecret should be set",
        "parameters": [
          "consumerSecret"
        ],
        "attributes": {}
      }
    ]
  }
]
```

@lburgazzoli , probably easy to fix. Just don't know where to start ;-)

**Comment by lburgazzoli** [comment]
Looks like we have an old dependency as when running on camel (master) I have:

    DefaultResultError{code='missing-option', description='httpUri should be set', parameters=[httpUri], attributes={}}

**Comment by rhuss** [comment]
Good to know, thanks for checking :) The snippet above is running on version 3.2.1 which is based on Camel [2.19.0.fuse-000020](https://repository.jboss.org/nexus/content/groups/ea/org/apache/camel/camel-core/2.19.0.fuse-000020/). This was build yesterday morning, but I have no idea on which camel version it is based.

For me its not clear from where this error message originate. Is it the conector or HttpComponent incldude in this project or comes it directly from the original Camel component (http4) ?

**Comment by lburgazzoli** [comment]
Ah sorry it is hpp4 so I need to check it again

**Comment by lburgazzoli** [comment]
ok, fixed upstream

**Comment by rhuss** [comment]
thx ;-)

**Comment by davsclaus** [comment]
There is a new 00031 version of EA assume its fixing this

**Comment by rhuss** [comment]
Note to myself: when updating I need to update ipaas-verifier, too since the ComponentVerifier API change substantially.

**Comment by davsclaus** [comment]
Okay upgraded on master branch and to SB 1.4.5 as well so it uses the same version as funktion

**Comment by davsclaus** [comment]
Mind that Camel 2.19 will be on SB 1.5.x and ideally we should get funktion upgraded as well

**Comment by rhuss** [comment]
Thanks !

So I'd better hurry up ;-) ....

**Comment by davsclaus** [comment]
Closing as we have upgraded here
