### ISSUE TITLE
Release new version of connectors

### ISSUE THREAD

**Issue by davsclaus** [syndesisio/connectors#34]
The trade-insight-buy connector is now scheduled. 

And there is a new EA build of fuse-camel: 2.19.0.fuse-000036

**Comment by davsclaus** [comment]
@rhuss just a heads up that there is a new EA build of camel: 2.19.0.fuse-000036

**Comment by rhuss** [comment]
thanks for the heads up, will update the ipaas-verifier accordingly.

**Comment by davsclaus** [comment]
@jimmidyson has released a new version
