### ISSUE TITLE
Upgrade Camel Version to pull in Extensions

### ISSUE THREAD

**Issue by KurtStam** [syndesisio/connectors#59]
We are at 2.19.0 now and the sql-stored-example overrides this with a newer version build by the Fuse team. We need to apply this version in the parent pom, however this will require some updates to the existing connectors because of an naming convention change.

**Comment by lburgazzoli** [comment]
To change this we should also change stuffs in syndesis-rest as there are also some underlying changes on how the connectors are configured (it also relates to https://github.com/syndesisio/syndesis-rest/issues/399).

Is this required for TP1 ?

**Comment by KurtStam** [comment]
If we want to go out with dynamic Salesforce & SqlStored procs then yes. We are using the extensions there. I don't think we want to go out with 2 versions of Camel?

**Comment by zregvart** [comment]
I don't think we have much choice now, we can't have dynamic stuff without MetadataExtension's. The option would be to contain this only within the `syndesis-verifier` but having a unified Camel version across `syndesis-verifier` and `runtime` I think is a must.

**Comment by jimmidyson** [comment]
Agreed it needs to be consistent

**Comment by lburgazzoli** [comment]
ok, will have a look

**Comment by lburgazzoli** [comment]
Should we close this as it has been merged ?

**Comment by jimmidyson** [comment]
Fixed by #61
