### ISSUE TITLE
UI text for connector descriptions should have consistent style across connectors

### ISSUE THREAD

**Issue by TovaCohen** [syndesisio/connectors#8]
For example, the sprint 8 demo shows this in the Connections page:

    Salesforce Upsert Contact
    Connection to Create or Update Salesforce Contact SObject

    Twitter Mention
    Connection from twitter when anyone mentions you

The Salesforce description capitalizes each important word. The Twitter description capitalizes only the first word. One convention should be chosen and implemented throughout. I know this seems trivial, but this kind of consistency creates a flow that speeds the user's understanding. Also, "Twitter" should always be capitalized.

**Comment by davsclaus** [comment]
I have updated the descriptions in this commit:
https://github.com/redhat-ipaas/connectors/commit/02625a7b1ca03a6607bd3e54a299f5e2dc77f1f3

Would you mind take a look, and we can change the descriptions to your liking. You can provide a github PR if you want a change or just write here in the comment and I can change it
