### ISSUE TITLE
Refactor the SQL Stored connector

### ISSUE THREAD

**Issue by zregvart** [syndesisio/connectors#84]
We currently fiddle with the _AutoConfiguration_ to create DataSource, this could be moved to be the responsibility of the SQL Stored connector component.

The `template` parameter could be generated on endpoint creation in the SQL Stored connector component.

This would allow us to use the Camel Maven tooling to build the JSON descriptors and remove the workaround that removes the options that are not declared on the endpoint.

**Comment by zregvart** [comment]
See the discussion on https://github.com/syndesisio/connectors/pull/79

**Comment by KurtStam** [comment]
@zregvart I think all of this has been done, except for maybe the template generation. Is think we can leave that the way it is?
